fn main() -> Result<(), devnet::error::DevnetError> {
    devnet::app::run()
} 